import { Company, Project, User, InterfaceRequest, Notification, SLAConfig, Message } from "@/types";

export const COMPANIES: Company[] = [
  { id: "c1", name: "PT Konstruksi Utama", code: "KON1", type: "contractor" },
  { id: "c2", name: "PT Mitra Teknik", code: "KON2", type: "contractor" },
  { id: "c3", name: "PT Rekayasa Abadi", code: "KON3", type: "contractor" },
  { id: "c-client", name: "PT Energi Nasional (Client)", code: "CLIENT", type: "client" },
];

export const PROJECTS: Project[] = [
  { id: "p1", name: "LNG Terminal Expansion Phase 2", code: "LNG-EXP-P2", isActive: true },
  { id: "p2", name: "Offshore Pipeline EPCI", code: "OFP-EPCI-01", isActive: true },
  { id: "p3", name: "Onshore Processing Facility", code: "OPF-2024", isActive: false },
];

export const USERS: User[] = [
  {
    id: "u1", name: "Ahmad Rizky", email: "superuser@epci-ims.com",
    role: "super_user", companyId: "c-client",
    company: COMPANIES[3], projectIds: ["p1", "p2", "p3"],
    isActive: true, avatarInitials: "AR",
  },
  {
    id: "u2", name: "Budi Santoso", email: "manager.kon1@epci-ims.com",
    role: "manager", companyId: "c1",
    company: COMPANIES[0], projectIds: ["p1", "p2"],
    isActive: true, avatarInitials: "BS",
  },
  {
    id: "u3", name: "Citra Dewi", email: "user.kon1@epci-ims.com",
    role: "user", companyId: "c1",
    company: COMPANIES[0], projectIds: ["p1"],
    isActive: true, avatarInitials: "CD",
  },
  {
    id: "u4", name: "Dewi Rahayu", email: "manager.kon2@epci-ims.com",
    role: "manager", companyId: "c2",
    company: COMPANIES[1], projectIds: ["p1", "p2"],
    isActive: true, avatarInitials: "DR",
  },
  {
    id: "u5", name: "Eko Prasetyo", email: "user.kon2@epci-ims.com",
    role: "user", companyId: "c2",
    company: COMPANIES[1], projectIds: ["p1"],
    isActive: true, avatarInitials: "EP",
  },
  {
    id: "u6", name: "Farida Hanum", email: "client@epci-ims.com",
    role: "client", companyId: "c-client",
    company: COMPANIES[3], projectIds: ["p1", "p2", "p3"],
    isActive: true, avatarInitials: "FH",
  },
  {
    id: "u7", name: "Gilang Ramadhan", email: "padmin@epci-ims.com",
    role: "project_admin", companyId: "c-client",
    company: COMPANIES[3], projectIds: ["p1"],
    isActive: true, avatarInitials: "GR",
  },
  {
    id: "u8", name: "Hani Pertiwi", email: "user.kon3@epci-ims.com",
    role: "user", companyId: "c3",
    company: COMPANIES[2], projectIds: ["p2"],
    isActive: false, avatarInitials: "HP",
  },
];

export const INTERFACE_REQUESTS: InterfaceRequest[] = [
  {
    id: "ir1",
    irNumber: "IR-KON1-KON2-0001",
    title: "Structural Load Data for Offshore Platform Module A",
    description: "Request for detailed structural load calculations for Module A integration with KON2 fabrication scope. This data is required for final design validation of connecting structures.",
    priority: "critical",
    status: "awaiting_response",
    requestorCompanyId: "c1", requestorCompany: COMPANIES[0],
    responderCompanyId: "c2", responderCompany: COMPANIES[1],
    requestorUserId: "u3", requestorUser: USERS[2],
    projectId: "p1", project: PROJECTS[0],
    dueDate: "2026-05-20",
    revision: 0,
    workflowLogs: [
      { id: "wl1", irId: "ir1", step: "Submission", action: "Draft Created", actorId: "u3", actorName: "Citra Dewi", actorRole: "user", timestamp: "2026-04-20T08:00:00Z" },
      { id: "wl2", irId: "ir1", step: "Submission", action: "Submitted for Manager Approval", actorId: "u3", actorName: "Citra Dewi", actorRole: "user", timestamp: "2026-04-21T09:00:00Z" },
      { id: "wl3", irId: "ir1", step: "Manager Authorization", action: "Authorized", actorId: "u2", actorName: "Budi Santoso", actorRole: "manager", comment: "Approved for submission.", timestamp: "2026-04-21T14:00:00Z" },
      { id: "wl4", irId: "ir1", step: "Request Validation", action: "Client Approved", actorId: "u6", actorName: "Farida Hanum", actorRole: "client", comment: "Request is valid and complete.", timestamp: "2026-04-23T10:00:00Z" },
    ],
    attachments: [
      { id: "att1", irId: "ir1", filename: "Module_A_Scope.pdf", size: 2048000, uploadedBy: "Citra Dewi", uploadedAt: "2026-04-20T08:30:00Z", type: "request" },
    ],
    createdAt: "2026-04-20T08:00:00Z",
    updatedAt: "2026-04-23T10:00:00Z",
  },
  {
    id: "ir2",
    irNumber: "IR-KON1-KON2-0002",
    title: "Electrical Cable Routing Through KON2 Area",
    description: "Interface request for electrical cable routing coordination through KON2 fabrication area. Need approval for penetration locations and cable tray supports.",
    priority: "non_critical",
    status: "awaiting_request_validation",
    requestorCompanyId: "c1", requestorCompany: COMPANIES[0],
    responderCompanyId: "c2", responderCompany: COMPANIES[1],
    requestorUserId: "u3", requestorUser: USERS[2],
    projectId: "p1", project: PROJECTS[0],
    dueDate: "2026-05-28",
    revision: 0,
    workflowLogs: [
      { id: "wl5", irId: "ir2", step: "Submission", action: "Draft Created", actorId: "u3", actorName: "Citra Dewi", actorRole: "user", timestamp: "2026-05-01T10:00:00Z" },
      { id: "wl6", irId: "ir2", step: "Submission", action: "Submitted", actorId: "u3", actorName: "Citra Dewi", actorRole: "user", timestamp: "2026-05-02T09:00:00Z" },
      { id: "wl7", irId: "ir2", step: "Manager Authorization", action: "Authorized", actorId: "u2", actorName: "Budi Santoso", actorRole: "manager", timestamp: "2026-05-02T15:00:00Z" },
    ],
    attachments: [],
    createdAt: "2026-05-01T10:00:00Z",
    updatedAt: "2026-05-02T15:00:00Z",
  },
  {
    id: "ir3",
    irNumber: "IR-KON2-KON3-0001",
    title: "Piping Isometrics for Tie-In Point TP-003",
    description: "KON2 requires piping isometric drawings for tie-in point TP-003 from KON3 scope to proceed with spool fabrication.",
    priority: "critical",
    status: "awaiting_response_validation",
    requestorCompanyId: "c2", requestorCompany: COMPANIES[1],
    responderCompanyId: "c3", responderCompany: COMPANIES[2],
    requestorUserId: "u5", requestorUser: USERS[4],
    projectId: "p2", project: PROJECTS[1],
    dueDate: "2026-05-10",
    revision: 0,
    response: {
      id: "resp1", irId: "ir3",
      content: "Please find attached the piping isometric drawings for tie-in point TP-003. These drawings are at IFR (Issued for Review) status. Key dimensions: NPS 8\", Class 600, Material CS A106 Gr.B. Insulation: None. Note that final IFC drawings will follow after review comments.",
      submittedBy: "Guntur Wicaksono", submittedAt: "2026-05-08T11:00:00Z",
      attachments: [
        { id: "att2", irId: "ir3", filename: "ISO-TP003-KON3-IFR.pdf", size: 5120000, uploadedBy: "Guntur Wicaksono", uploadedAt: "2026-05-08T11:00:00Z", type: "response" },
        { id: "att3", irId: "ir3", filename: "Material_List_TP003.xlsx", size: 256000, uploadedBy: "Guntur Wicaksono", uploadedAt: "2026-05-08T11:05:00Z", type: "response" },
      ],
    },
    workflowLogs: [
      { id: "wl8", irId: "ir3", step: "Submission", action: "Draft Created", actorId: "u5", actorName: "Eko Prasetyo", actorRole: "user", timestamp: "2026-04-25T08:00:00Z" },
      { id: "wl9", irId: "ir3", step: "Manager Authorization", action: "Authorized", actorId: "u4", actorName: "Dewi Rahayu", actorRole: "manager", timestamp: "2026-04-25T16:00:00Z" },
      { id: "wl10", irId: "ir3", step: "Request Validation", action: "Client Approved", actorId: "u6", actorName: "Farida Hanum", actorRole: "client", timestamp: "2026-04-27T09:00:00Z" },
      { id: "wl11", irId: "ir3", step: "Response", action: "Response Submitted", actorId: "u7", actorName: "Guntur Wicaksono", actorRole: "manager", timestamp: "2026-05-08T11:00:00Z" },
    ],
    attachments: [],
    createdAt: "2026-04-25T08:00:00Z",
    updatedAt: "2026-05-08T11:00:00Z",
  },
  {
    id: "ir4",
    irNumber: "IR-KON1-KON3-0001",
    title: "HVAC Duct Penetration Coordinates – Module B",
    description: "Request for coordinates and dimensions of HVAC duct penetrations through Module B structural bulkhead designed by KON3.",
    priority: "non_critical",
    status: "closed",
    requestorCompanyId: "c1", requestorCompany: COMPANIES[0],
    responderCompanyId: "c3", responderCompany: COMPANIES[2],
    requestorUserId: "u2", requestorUser: USERS[1],
    projectId: "p1", project: PROJECTS[0],
    dueDate: "2026-04-15",
    revision: 1,
    response: {
      id: "resp2", irId: "ir4",
      content: "HVAC duct penetration coordinates and dimensions are provided as per attachment. All penetrations are within structural limits as confirmed by structural team. Fire seal requirements apply per Spec S-001.",
      submittedBy: "Hani Pertiwi", submittedAt: "2026-04-10T14:00:00Z",
      attachments: [
        { id: "att4", irId: "ir4", filename: "HVAC_Penetration_Coords_Rev1.pdf", size: 1024000, uploadedBy: "Hani Pertiwi", uploadedAt: "2026-04-10T14:00:00Z", type: "response" },
      ],
    },
    workflowLogs: [
      { id: "wl12", irId: "ir4", step: "Submission", action: "Draft Created", actorId: "u2", actorName: "Budi Santoso", actorRole: "manager", timestamp: "2026-03-15T08:00:00Z" },
      { id: "wl13", irId: "ir4", step: "Request Validation", action: "Client Approved", actorId: "u6", actorName: "Farida Hanum", actorRole: "client", timestamp: "2026-03-18T10:00:00Z" },
      { id: "wl14", irId: "ir4", step: "Response", action: "Response Submitted", actorId: "u8", actorName: "Hani Pertiwi", actorRole: "user", timestamp: "2026-04-01T09:00:00Z" },
      { id: "wl15", irId: "ir4", step: "IR Recycle", action: "More Info Requested", actorId: "u2", actorName: "Budi Santoso", actorRole: "manager", comment: "Need revised coordinates for penetration P-04.", timestamp: "2026-04-02T11:00:00Z" },
      { id: "wl16", irId: "ir4", step: "IR Recycle", action: "Recycle Approved (Rev 1)", actorId: "u6", actorName: "Farida Hanum", actorRole: "client", timestamp: "2026-04-03T09:00:00Z" },
      { id: "wl17", irId: "ir4", step: "Response", action: "Response Resubmitted Rev 1", actorId: "u8", actorName: "Hani Pertiwi", actorRole: "user", timestamp: "2026-04-10T14:00:00Z" },
      { id: "wl18", irId: "ir4", step: "Response Acceptance", action: "Accepted by Requestor", actorId: "u2", actorName: "Budi Santoso", actorRole: "manager", timestamp: "2026-04-12T10:00:00Z" },
      { id: "wl19", irId: "ir4", step: "Close Out", action: "Closed", actorId: "u6", actorName: "Farida Hanum", actorRole: "client", comment: "All information received and accepted. IR formally closed.", timestamp: "2026-04-14T16:00:00Z" },
    ],
    attachments: [],
    closeOutDate: "2026-04-14T16:00:00Z",
    closeOutComment: "All information received and accepted. IR formally closed.",
    createdAt: "2026-03-15T08:00:00Z",
    updatedAt: "2026-04-14T16:00:00Z",
  },
  {
    id: "ir5",
    irNumber: "IR-KON2-KON1-0001",
    title: "Instrument Cable Schedule – Area 300",
    description: "KON2 requires the instrument cable schedule for Area 300 to verify cable tray fill capacity and routing conflicts.",
    priority: "critical",
    status: "draft",
    requestorCompanyId: "c2", requestorCompany: COMPANIES[1],
    responderCompanyId: "c1", responderCompany: COMPANIES[0],
    requestorUserId: "u5", requestorUser: USERS[4],
    projectId: "p1", project: PROJECTS[0],
    dueDate: "2026-06-01",
    revision: 0,
    workflowLogs: [
      { id: "wl20", irId: "ir5", step: "Submission", action: "Draft Created", actorId: "u5", actorName: "Eko Prasetyo", actorRole: "user", timestamp: "2026-05-14T10:00:00Z" },
    ],
    attachments: [],
    createdAt: "2026-05-14T10:00:00Z",
    updatedAt: "2026-05-14T10:00:00Z",
  },
  {
    id: "ir6",
    irNumber: "IR-KON1-KON2-0003",
    title: "Civil Foundation Load Data – Compressor Skid CS-01",
    description: "Foundation load data required for compressor skid CS-01 interface between KON1 civil scope and KON2 mechanical scope.",
    priority: "critical",
    status: "awaiting_closeout",
    requestorCompanyId: "c1", requestorCompany: COMPANIES[0],
    responderCompanyId: "c2", responderCompany: COMPANIES[1],
    requestorUserId: "u2", requestorUser: USERS[1],
    projectId: "p2", project: PROJECTS[1],
    dueDate: "2026-05-18",
    revision: 0,
    response: {
      id: "resp3", irId: "ir6",
      content: "Civil foundation load data for CS-01: Operating weight 45T, Empty weight 28T, Wind load 12kN (N-S), 9kN (E-W). Anchor bolt pattern: 8 x M36 on 1200x900 BC. Grout thickness: 50mm nom.",
      submittedBy: "Dewi Rahayu", submittedAt: "2026-05-12T09:00:00Z",
      attachments: [],
    },
    workflowLogs: [
      { id: "wl21", irId: "ir6", step: "Submission", action: "Submitted", actorId: "u2", actorName: "Budi Santoso", actorRole: "manager", timestamp: "2026-04-28T09:00:00Z" },
      { id: "wl22", irId: "ir6", step: "Request Validation", action: "Client Approved", actorId: "u6", actorName: "Farida Hanum", actorRole: "client", timestamp: "2026-04-30T10:00:00Z" },
      { id: "wl23", irId: "ir6", step: "Response", action: "Response Submitted", actorId: "u4", actorName: "Dewi Rahayu", actorRole: "manager", timestamp: "2026-05-12T09:00:00Z" },
      { id: "wl24", irId: "ir6", step: "Response Validation", action: "Client Approved", actorId: "u6", actorName: "Farida Hanum", actorRole: "client", timestamp: "2026-05-13T11:00:00Z" },
      { id: "wl25", irId: "ir6", step: "Response Acceptance", action: "Requestor Accepted", actorId: "u2", actorName: "Budi Santoso", actorRole: "manager", timestamp: "2026-05-14T09:00:00Z" },
    ],
    attachments: [],
    createdAt: "2026-04-28T08:00:00Z",
    updatedAt: "2026-05-14T09:00:00Z",
  },
  {
    id: "ir7",
    irNumber: "IR-KON3-KON1-0001",
    title: "Flare Tip Elevation Impact on Structural Clearance",
    description: "KON3 needs structural clearance confirmation from KON1 for flare tip elevation change from +65m to +72m AGL.",
    priority: "critical",
    status: "ir_recycle",
    requestorCompanyId: "c3", requestorCompany: COMPANIES[2],
    responderCompanyId: "c1", responderCompany: COMPANIES[0],
    requestorUserId: "u7", requestorUser: USERS[6],
    projectId: "p1", project: PROJECTS[0],
    dueDate: "2026-05-22",
    revision: 1,
    response: {
      id: "resp4", irId: "ir7",
      content: "Initial clearance check done. However, revised elevation to 72m AGL creates conflict with crane pedestal at grid G-5. Further study required.",
      submittedBy: "Budi Santoso", submittedAt: "2026-05-05T14:00:00Z",
      attachments: [],
    },
    workflowLogs: [
      { id: "wl26", irId: "ir7", step: "Submission", action: "Submitted", actorId: "u7", actorName: "Guntur Wicaksono", actorRole: "manager", timestamp: "2026-04-22T08:00:00Z" },
      { id: "wl27", irId: "ir7", step: "Request Validation", action: "Client Approved", actorId: "u6", actorName: "Farida Hanum", actorRole: "client", timestamp: "2026-04-24T10:00:00Z" },
      { id: "wl28", irId: "ir7", step: "Response", action: "Response Submitted", actorId: "u2", actorName: "Budi Santoso", actorRole: "manager", timestamp: "2026-05-05T14:00:00Z" },
      { id: "wl29", irId: "ir7", step: "Response Validation", action: "Client Approved", actorId: "u6", actorName: "Farida Hanum", actorRole: "client", timestamp: "2026-05-06T09:00:00Z" },
      { id: "wl30", irId: "ir7", step: "Response Acceptance", action: "More Info Required", actorId: "u7", actorName: "Guntur Wicaksono", actorRole: "manager", comment: "Crane conflict must be resolved.", timestamp: "2026-05-07T11:00:00Z" },
      { id: "wl31", irId: "ir7", step: "IR Recycle", action: "Recycle Approved (Rev 1)", actorId: "u6", actorName: "Farida Hanum", actorRole: "client", timestamp: "2026-05-08T09:00:00Z" },
    ],
    attachments: [],
    createdAt: "2026-04-22T08:00:00Z",
    updatedAt: "2026-05-08T09:00:00Z",
  },
];

export const NOTIFICATIONS: Notification[] = [
  { id: "n1", userId: "u6", irId: "ir2", irNumber: "IR-KON1-KON2-0002", type: "ir_submitted", message: "New IR IR-KON1-KON2-0002 submitted for your validation: 'Electrical Cable Routing Through KON2 Area'", isRead: false, createdAt: "2026-05-02T15:00:00Z" },
  { id: "n2", userId: "u6", irId: "ir3", irNumber: "IR-KON2-KON3-0001", type: "response_submitted", message: "Response submitted for IR-KON2-KON3-0001. Awaiting your validation.", isRead: false, createdAt: "2026-05-08T11:00:00Z" },
  { id: "n3", userId: "u6", irId: "ir1", irNumber: "IR-KON1-KON2-0001", type: "sla_warning", message: "SLA Warning: IR-KON1-KON2-0001 is due in 4 days. Response still pending.", isRead: false, createdAt: "2026-05-16T08:00:00Z" },
  { id: "n4", userId: "u2", irId: "ir1", irNumber: "IR-KON1-KON2-0001", type: "ir_approved", message: "Your IR IR-KON1-KON2-0001 has been validated by Client. KON2 is now responding.", isRead: true, createdAt: "2026-04-23T10:00:00Z" },
  { id: "n5", userId: "u4", irId: "ir1", irNumber: "IR-KON1-KON2-0001", type: "ir_submitted", message: "You have a new interface request to respond: IR-KON1-KON2-0001 - Structural Load Data", isRead: true, createdAt: "2026-04-23T10:00:00Z" },
  { id: "n6", userId: "u2", irId: "ir6", irNumber: "IR-KON1-KON2-0003", type: "response_approved", message: "Response for IR-KON1-KON2-0003 accepted. Pending Client close out.", isRead: false, createdAt: "2026-05-14T09:00:00Z" },
  { id: "n7", userId: "u7", irId: "ir7", irNumber: "IR-KON3-KON1-0001", type: "recycle_approved", message: "IR Recycle Rev 1 approved for IR-KON3-KON1-0001. KON1 must now submit updated response.", isRead: false, createdAt: "2026-05-08T09:00:00Z" },
];

export const SLA_CONFIGS: SLAConfig[] = [
  { id: "sla1", projectId: "p1", priority: "critical", daysRequestValidation: 3, daysResponse: 14, daysResponseValidation: 3, daysCloseOut: 5 },
  { id: "sla2", projectId: "p1", priority: "non_critical", daysRequestValidation: 5, daysResponse: 21, daysResponseValidation: 5, daysCloseOut: 7 },
  { id: "sla3", projectId: "p2", priority: "critical", daysRequestValidation: 3, daysResponse: 14, daysResponseValidation: 3, daysCloseOut: 5 },
  { id: "sla4", projectId: "p2", priority: "non_critical", daysRequestValidation: 5, daysResponse: 21, daysResponseValidation: 5, daysCloseOut: 7 },
];

export const MESSAGES: Message[] = [
  // Admin (u1) and Client (u6) conversation
  { id: "m1", senderId: "u1", receiverId: "u6", content: "Hi Farida, could you please review the new SLA configuration for LNG-EXP-P2?", timestamp: "2026-05-15T09:00:00Z", isRead: true },
  { id: "m2", senderId: "u6", receiverId: "u1", content: "Sure, I'll take a look this afternoon. Have we aligned with KON1 on this?", timestamp: "2026-05-15T09:15:00Z", isRead: true },
  { id: "m3", senderId: "u1", receiverId: "u6", content: "Yes, Budi from KON1 has agreed to the 14-day critical response time.", timestamp: "2026-05-15T09:20:00Z", isRead: true },
  
  // Manager KON1 (u2) and Client (u6) conversation
  { id: "m4", senderId: "u2", receiverId: "u6", content: "Regarding IR-KON1-KON2-0003, we need an extension on the close out.", timestamp: "2026-05-15T14:30:00Z", isRead: false },
  
  // Manager KON1 (u2) and Manager KON2 (u4) conversation
  { id: "m5", senderId: "u2", receiverId: "u4", content: "Dewi, when can we expect the response for IR-KON1-KON2-0001?", timestamp: "2026-05-16T10:00:00Z", isRead: false },
];
